urls.py
from django.contrib import admin
from django.urls import path
from my_expenses import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


app_name = 'exp'

urlpatterns = [
    path('', views.home),
    path('upload/', views.upload, name="Upload"),
    #path('upload/', views.expense_form),
    path('index/', views.expenses_list, name="List"),
    path('index/expense_form/', views.expense_form, name="Expense Entry"),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.expense_delete, name='expense_delete'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.expense_edit, name='expense_edit'),
]

#if settings.DEBUG:
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models.py
from django.db import models
from django.utils import timezone

class Expense(models.Model):
    expense_name = models.CharField(max_length=100, default="Expense Name")
    description = models.CharField(max_length=240)  
    recepit_date = models.DateField(max_length=10)
    receipt_num = models.CharField(max_length=32, default="1")
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    vat_perc = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    vat_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    subtotal = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    vendor_name = models.CharField(max_length=100, default="Vendor")
    vendor_vat = models.CharField(max_length=20, default=" ")
    vendor_address = models.CharField(max_length=100, default="address")
    country = models.CharField(max_length=30, default="España")
    category = models.CharField(max_length=100, default="category")
    attachment = models.ImageField(upload_to="receipts/")

    class Meta:
        db_table = "expense_record"

    def __str__(self) -> str:
        return self.expense_name

# Create your models here.
"""class MyExpenses(models.Model):
    expense_name = models.CharField(max_length=100, default="Expense Name")
    description = models.CharField(max_length=240, default="Description")  
    recepit_date = models.DateField(max_length=10, default=timezone.now)
    receipt_num = models.CharField(max_length=32, default="1")
    total = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    vat_perc = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    vat_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    subtotal = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    vendor_name = models.CharField(max_length=100, default="Vendor")
    vendor_vat = models.CharField(max_length=20, default=" ")
    vendor_address = models.CharField(max_length=100, default="address")
    country = models.CharField(max_length=30, default="España")
    category = models.CharField(max_length=100, default="category")
    attachment = models.FileField(upload_to="receipts/")

    def __str__(self) -> str:
        return self.expense_name"""

forms.py
from django import forms
from .models import Expense
from .widgets import BootstrapDateTimePickerInput

class expenseEntry(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ('expense_name', 'description', 'category', 'recepit_date', 'receipt_num', 'total', 'vat_perc', 'vat_amount', 'subtotal', 'vendor_name', 'vendor_vat', 'vendor_address', 'country', 'attachment')
        widgets = {
            'expense_name' : forms.TextInput(attrs={'class': 'form-control'}),
            'description' : forms.Textarea(attrs={'class': 'form-control'}),
            'category' : forms.TextInput(attrs={'class': 'form-control'}),
            'receipt_num' : forms.NumberInput(attrs={'class': 'form-control'}),
            'total' : forms.NumberInput(attrs={'class': 'form-control'}),
            'vat_perc' : forms.NumberInput(attrs={'class': 'form-control'}),
            'vat_amount' : forms.NumberInput(attrs={'class': 'form-control'}),
            'subtotal' : forms.NumberInput(attrs={'class': 'form-control'}),
            'vendor_name' : forms.TextInput(attrs={'class': 'form-control'}),
            'vendor_vat' : forms.TextInput(attrs={'class': 'form-control'}),
            'vendor_address' : forms.TextInput(attrs={'class': 'form-control'}),
            'country' : forms.TextInput(attrs={'class': 'form-control'}),
            'attachment' : forms.FileInput(attrs={'class': 'form-control-file'}),
            'receipt_date' : forms.DateTimeField(
                input_formats=['%d/%m/%Y'], 
                widget=BootstrapDateTimePickerInput(),
                )
        }

views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from .models import Expense
from .forms import expenseEntry
from django.contrib import messages

# Create your views here.

def home(request):
    return render(request, 'my_expenses/base.html',)

def upload(request):
    context = {}
    if request.method == "POST":
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['request', 'my_expenses/upload.html'] = fs.url(name)
    return render(request, 'my_expenses/upload.html', context)

def expenses_list(request):
    all_expenses = Expense.objects.all()
    return render(request, 'my_expenses/index.html', {'all_expenses': all_expenses})

def expense_edit(request, pk):
    expense = get_object_or_404(Expense, pk=pk)
    if request.method == "POST":
        expense.save()
        return redirect(    'my_expenses/expense_form.html')
    return render(request, 'my_expenses/index.html', {'expense': expense})

def expense_delete(request, pk):
    expense = get_object_or_404(Expense, pk=pk)
    if request.method == "POST":
        expense.delete()
        return redirect("../../index/")
    return render(request, 'my_expenses/index.html', {'expense': expense})

def expense_form(request):
    if request.method == 'POST':
        form = expenseEntry(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            img_obj = form.instance
            messages.success(request, 'Form submission successful')
            return render(request, 'my_expenses/index.html', {'form': form, 'img_obj': img_obj})
    else:
        form = expenseEntry()
    return render(request, 'my_expenses/expense_form.html', {
        'form' : form
        })

templates/my_expenses/Base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <title>{% block title %}Expensor{% endblock %}</title>
</head>

<body style="background-color: #a1d883;">
    {% block navbar %}
        <header class="" style="display: flex; background-color: white; padding: 1rem;">
            <nav class="navbar navbar-expand-lg">
                <span class="d-inline-flex">
                    <h1>Expensor</h1>
                </span>
                <ul class="navbar-nav ml-5">
                    <li class="nav-item">
                        <a class="nav-link active" href="/my_expenses/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/my_expenses/index/expense_form/">Upload</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="/my_expenses/index/">See All</a>
                    </li>
                </ul>    
            </nav>
        </header>
    {% endblock %}


    <div>
        {% block list_display %}   
        {% endblock %}
    </div>
    <div class="form-group">
        {% block form %}   
        {% endblock %}
    </div>
</body>
</html>

templates/my_expenses/expense_form.html
{% extends 'my_expenses/Base.html' %}

{% block container %}
    <div class="form-group m-3">
        <form type="form-group" method="POST" enctype="multipart/form-data" class="p-3 card col-sm-6 mx-auto p-10 shadow p-4 mb-4 bg-white">
            <h4 class="shadow p-4 mb-4" style="background-color: rgb(126, 175, 163);">New Record</h4>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>
    </div>
    {% if url %}
    <p>Uploaded file:<a href="{{ url }}">{{ url }}</a></p>
    <img src="{{ expense.image.url }}" alt="connect" style="max-height:300px">
    {% endif %}
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li  {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
        {% endfor %}
        </ul>
    {% endif %}

{% endblock %}

templates/my_expenses/index.html
{% extends 'my_expenses/Base.html' %}
{% load static %}
{% block list_display %}  
    <div class="container">
        {% for expense in all_expenses %}
            <div class="card p-3 m-3">
                <div style="float: left;;">
                    <a href="{% static expense.attachment.url %}" target="_blank"><img src="{% static expense.attachment.url %}" alt="Receipt" style="max-height:100px"></a>
                </div>
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Category</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ expense.expense_name }}</td>
                            <td>{{ expense.description }}</td>
                            <td>{{ expense.category }}</td>
                            <td>{{ expense.total }}</td>
                        </tr>
                    </tbody>
                </table>
                <form action="{% url 'exp:expense_edit' expense.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Update expense">
                </form>     
                <form action="{% url 'exp:expense_delete' expense.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Delete expense">
                </form> 
            </div>
        {% endfor %}
    </div>
{% endblock %}
</body>
</html>

templates/my_expenses/upload.html
{% extends 'my_expenses/Base.html' %}

{% block container %}

    <div class="container">
        <form  type="form-group" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <h2>New Item</h2>
            <div class="form-group">
                <label for="vendor">Vendor</label>
                <input type="text" placeholder="" class="form-control" id="vendor" required/>
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <input type="text" placeholder="" class="form-control" id="description" required/>
            </div>
            <div class="form-group">
                <label for="total">Total</label>
                <div class="input-group">
                    <span class="input-group-addon">€</span>
                    <input type="number" value="1000" min="0" step="0.01" data-number-to-fixed="2" data-number-stepfactor="100" class="form-control currency" id="total"/>
                </div>
            </div>  
            <div class="custom-file">
                <input type="file" name="document" class="custom-file-input" id="inputGroupFile01"/>
                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
            </div>
            <div class="form-group pt-3">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    {% if url %}
        <p>Uploaded file:<a href="{{ url }}">{{ url }}</a></p>
        <img src="{{ expense.image.url }}" alt="connect" style="max-height:300px">
    {% endif %}

{% endblock %}